### ISSUE TITLE
ROADMAP-2015

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#46]
Thought I'd create this issue so we can share idea and plans..
These are the things in mind.. Please change to requirements.. but these relate to infrastruct

v0.5
==========
Current release is 0.5 and last with pyqt4
We are moving from sf to github

v0.6
==========================
- [X] New release that is PyQt5 = Python3 only
- [X] Announce move and infrastructure to github
- [X] New home page, et all
- [X] Also Data is now json and in ts2-data
- [X] Ability to download sims / signals from ts2-data
- [X] Trains shunting
- [ ] Trains joining / splitting
- [X] New parametric signals
- [X] French BAL signals (except blinking)
- [ ] UK Shunt signals
- [ ] UI improvements (toolbars, etc.)
- [ ] Catch exceptions when loading sims

v0.7
=======================
- [ ] New Online server to share data and front end to ts2 data
- [ ] Inbuilt server
- [ ] Import sims from other simulators (traindir & railway operation simulator for a start).
- [ ] blinking signal aspects
- [ ] Points delay and interlocking
- [ ] Radio communication with drivers
- [ ] ARS

v0.8
=======================
- [ ] Multi-player gaming by connecting several ts2 instances via websocket

**Comment by pedromorgan** [comment]
OK we got an IRC channel at `irc.freenode.net#TrainSigSim` ;-) #ts2 was taken ;-(

**Comment by npiganeau** [comment]
Good idea !

**Comment by npiganeau** [comment]
Updated roadmap post

**Comment by Sharpe49** [comment]
French signalling is not finished : blinking indications are not implemented.

**Comment by Sharpe49** [comment]
And, by the way, the roadmap should probably be moved in the Wiki.

**Comment by npiganeau** [comment]
@Sharpe49 you're right, I need to develop blinking aspects to be able to fully finish French signalling.

And I'll move this to the wiki.

**Comment by npiganeau** [comment]
Moved to wiki.
